global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # ARIA API metrics
  - job_name: 'aria-api'
    static_configs:
      - targets: [ 'aria-api:8000' ]
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Redis exporter (if using)
  - job_name: 'redis'
    static_configs:
      - targets: [ 'redis-exporter:9121' ]

  # PostgreSQL exporter (if using)
  - job_name: 'postgres'
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: [ 'node-exporter:9100' ]

# Alerting rules
rule_files:
  - 'alerts.yml'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: [ ]
          # - 'alertmanager:9093'
